# Generated by Django 2.0.2 on 2018-03-13 05:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppStatus',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(max_length=50)),
                ('status_type', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'AppStatus',
                'verbose_name_plural': 'AppStatus',
            },
        ),
        migrations.CreateModel(
            name='InfographCategory',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('category', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'InfographCategory',
                'verbose_name_plural': 'InfographCategories',
            },
        ),
        migrations.CreateModel(
            name='ParentInfograph',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'ParentInfograph',
                'verbose_name_plural': 'ParentInfographs',
                'ordering': ['date_created'],
            },
        ),
    ]
