# Generated by Django 2.0.2 on 2018-03-13 05:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news_room', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSource',
            fields=[
                ('source_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('source', models.URLField(max_length=100)),
                ('source_type', models.CharField(max_length=50)),
                ('name', models.URLField(max_length=100)),
            ],
            options={
                'verbose_name': 'AppSource',
            },
        ),
        migrations.CreateModel(
            name='Infograph',
            fields=[
                ('i_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('p_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('c_id', models.PositiveIntegerField()),
                ('status_id', models.PositiveIntegerField()),
                ('source_id', models.PositiveIntegerField()),
                ('appsource', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news_room.AppSource')),
                ('appstatus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news_room.AppStatus')),
                ('infographcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news_room.InfographCategory')),
                ('parentinfograph', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news_room.ParentInfograph')),
            ],
            options={
                'verbose_name': 'Infograph',
                'verbose_name_plural': 'Infographs',
                'ordering': ['date_created'],
            },
        ),
    ]
