# Generated by Django 2.0.2 on 2018-03-13 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news_room', '0002_appsource_infograph'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterTopics',
            fields=[
                ('mt_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('master_topic_code', models.CharField(max_length=50)),
                ('master_topic', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'MasterTopic',
                'verbose_name_plural': 'MasterTopics',
            },
        ),
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('t_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('mt_id', models.PositiveIntegerField()),
                ('topic_code', models.CharField(max_length=50)),
                ('topicdescription', models.CharField(max_length=50)),
                ('mastertopics', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news_room.MasterTopics')),
            ],
            options={
                'verbose_name': 'Topic',
                'verbose_name_plural': 'Topics',
            },
        ),
    ]
