# Generated by Django 2.0.2 on 2018-04-11 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_room', '0002_auto_20180404_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topics',
            name='mastertopics',
        ),
    ]
