# Generated by Django 2.0.2 on 2018-04-11 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news_room', '0003_remove_topics_mastertopics'),
    ]

    operations = [
        migrations.AddField(
            model_name='topics',
            name='mastertopics',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news_room.MasterTopics'),
        ),
    ]
