# Generated by Django 2.0.2 on 2018-03-13 05:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news_room', '0004_custommetatags_entity_geopolitical'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfographAssociation',
            fields=[
                ('i_ad', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('i_id', models.PositiveIntegerField()),
                ('t_id', models.PositiveIntegerField()),
                ('mtg_id', models.PositiveIntegerField()),
                ('e_id', models.PositiveIntegerField()),
                ('gp_id', models.PositiveIntegerField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('status_id', models.PositiveIntegerField()),
                ('appstatus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news_room.AppStatus')),
                ('custommetatags', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news_room.CustomMetaTags')),
                ('entity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news_room.Entity')),
                ('geopolitical', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news_room.GeoPolitical')),
                ('infograph', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news_room.Infograph')),
                ('topics', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news_room.Topics')),
            ],
        ),
    ]
