# Generated by Django 2.0.2 on 2018-03-13 05:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news_room', '0007_audittype'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCustomMetaTags',
            fields=[
                ('umtg_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('u_id', models.PositiveIntegerField()),
                ('mtg_id', models.PositiveIntegerField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('status_id', models.PositiveIntegerField()),
                ('appstatus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news_room.AppStatus')),
                ('custommetatags', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news_room.CustomMetaTags')),
                ('users', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news_room.Users')),
            ],
        ),
        migrations.CreateModel(
            name='UserEntity',
            fields=[
                ('ue_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('u_id', models.PositiveIntegerField()),
                ('e_id', models.PositiveIntegerField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('status_id', models.PositiveIntegerField()),
                ('appstatus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news_room.AppStatus')),
                ('entity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news_room.Entity')),
                ('users', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news_room.Users')),
            ],
        ),
        migrations.CreateModel(
            name='UserGeoPolitical',
            fields=[
                ('upg_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('u_id', models.PositiveIntegerField()),
                ('gp_id', models.PositiveIntegerField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('status_id', models.PositiveIntegerField()),
                ('appstatus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news_room.AppStatus')),
                ('geopolitical', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news_room.GeoPolitical')),
                ('users', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news_room.Users')),
            ],
        ),
        migrations.CreateModel(
            name='UserTopic',
            fields=[
                ('ut_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('u_id', models.PositiveIntegerField()),
                ('t_id', models.PositiveIntegerField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('status_id', models.PositiveIntegerField()),
                ('appstatus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news_room.AppStatus')),
                ('topics', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news_room.Topics')),
                ('users', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news_room.Users')),
            ],
        ),
    ]
