# Generated by Django 2.0.2 on 2018-03-13 05:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news_room', '0008_usercustommetatags_userentity_usergeopolitical_usertopic'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssociationType',
            fields=[
                ('at_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('association', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserAssociations',
            fields=[
                ('ua_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('u_id1', models.PositiveIntegerField()),
                ('u_id2', models.PositiveIntegerField()),
                ('at_id', models.PositiveIntegerField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('status_id', models.PositiveIntegerField()),
                ('appstatus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news_room.AppStatus')),
                ('associationType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news_room.AssociationType')),
                ('users', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news_room.Users')),
            ],
        ),
    ]
