# Generated by Django 2.0.2 on 2018-03-13 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_room', '0010_appsettings_useraudit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appsource',
            name='name',
        ),
        migrations.AddField(
            model_name='appsource',
            name='domain_url',
            field=models.URLField(default='www.test.com', max_length=100),
        ),
        migrations.AddField(
            model_name='infograph',
            name='external_url',
            field=models.URLField(default='www.test1.com', max_length=100),
        ),
        migrations.AddField(
            model_name='infograph',
            name='internal_url',
            field=models.ImageField(default=1, upload_to='infograph.jpg'),
            preserve_default=False,
        ),
    ]
