# Generated by Django 2.0.2 on 2018-03-06 06:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('asid', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('appset', models.CharField(max_length=50)),
                ('appval', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'AppSetting',
                'verbose_name_plural': 'AppSettings',
            },
        ),
        migrations.CreateModel(
            name='AppSource',
            fields=[
                ('sourceID', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=100)),
                ('source_type', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'AppSource',
            },
        ),
        migrations.CreateModel(
            name='AppStatus',
            fields=[
                ('status_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=50)),
                ('status_type', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'AppStatus',
                'verbose_name_plural': 'AppStatus',
            },
        ),
        migrations.CreateModel(
            name='AssociationType',
            fields=[
                ('atid', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('association', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AuditType',
            fields=[
                ('auid', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('audit_type', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='CustomMetaTags',
            fields=[
                ('mtgid', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('metatag', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('eid', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('entitycode', models.CharField(max_length=50)),
                ('entitytype', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GeoPolitical',
            fields=[
                ('eid', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('gpcode', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Infograph',
            fields=[
                ('iid', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('pid', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('cid', models.PositiveIntegerField()),
                ('statusID', models.PositiveIntegerField()),
                ('sourceID', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Infograph',
                'verbose_name_plural': 'Infographs',
                'ordering': ['date_created'],
            },
        ),
        migrations.CreateModel(
            name='InfographAssociation',
            fields=[
                ('iad', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('iid', models.PositiveIntegerField()),
                ('tid', models.PositiveIntegerField()),
                ('mtgid', models.PositiveIntegerField()),
                ('eid', models.PositiveIntegerField()),
                ('gpid', models.PositiveIntegerField()),
                ('datecreated', models.DateTimeField(default=django.utils.timezone.now)),
                ('statusid', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='InfographCategory',
            fields=[
                ('pid', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('category', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'InfographCategory',
                'verbose_name_plural': 'InfographCategories',
            },
        ),
        migrations.CreateModel(
            name='MasterTopics',
            fields=[
                ('mtid', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('master_topic_code', models.CharField(max_length=50)),
                ('master_topic', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'MasterTopic',
                'verbose_name_plural': 'MasterTopics',
            },
        ),
        migrations.CreateModel(
            name='ParentInfograph',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False, verbose_name='pid')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('datecreated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'ParentInfograph',
                'verbose_name_plural': 'ParentInfographs',
                'ordering': ['datecreated'],
            },
        ),
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('tid', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('mtid', models.PositiveIntegerField()),
                ('topic_code', models.CharField(max_length=50)),
                ('topicdescription', models.CharField(max_length=50)),
                ('mastertopics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsroom.MasterTopics')),
            ],
            options={
                'verbose_name': 'Topic',
                'verbose_name_plural': 'Topics',
            },
        ),
        migrations.CreateModel(
            name='UserAssociations',
            fields=[
                ('uaid', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('uid1', models.PositiveIntegerField()),
                ('ud2', models.PositiveIntegerField()),
                ('atid', models.PositiveIntegerField()),
                ('datecreated', models.DateTimeField(default=django.utils.timezone.now)),
                ('statusid', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserAudit',
            fields=[
                ('uauid', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('uid', models.PositiveIntegerField()),
                ('auid', models.PositiveIntegerField()),
                ('elementid', models.PositiveIntegerField()),
                ('datecreated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='UserCustomMetaTags',
            fields=[
                ('umtgid', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('uid', models.PositiveIntegerField()),
                ('mtgid', models.PositiveIntegerField()),
                ('datecreated', models.DateTimeField(default=django.utils.timezone.now)),
                ('statusid', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserEntity',
            fields=[
                ('ueid', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('uid', models.PositiveIntegerField()),
                ('eid', models.PositiveIntegerField()),
                ('datecreated', models.DateTimeField(default=django.utils.timezone.now)),
                ('statusid', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserGeoPolitical',
            fields=[
                ('upgid', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('uid', models.PositiveIntegerField()),
                ('gpid', models.PositiveIntegerField()),
                ('datecreated', models.DateTimeField(default=django.utils.timezone.now)),
                ('statusid', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('uid', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=100)),
                ('pwd', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gpid', models.PositiveIntegerField()),
                ('status_id', models.PositiveIntegerField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='UserTopic',
            fields=[
                ('utid', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('uid', models.PositiveIntegerField()),
                ('tid', models.PositiveIntegerField()),
                ('datecreated', models.DateTimeField(default=django.utils.timezone.now)),
                ('statusid', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('usertypeid', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('usertype', models.CharField(max_length=50)),
            ],
        ),
    ]
