# Generated by Django 2.0.2 on 2018-03-09 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0002_auto_20180306_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infographcategory',
            name='p_id',
        ),
        migrations.AddField(
            model_name='infograph',
            name='appsource',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='newsroom.AppSource'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infograph',
            name='appstatus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='newsroom.AppStatus'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infograph',
            name='infograph_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Infographs', to='newsroom.InfographCategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infograph',
            name='parentinfograph',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='parentnfographs', to='newsroom.ParentInfograph'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infographcategory',
            name='c_id',
            field=models.PositiveIntegerField(default='as', primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appsource',
            name='source_id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='appstatus',
            name='status_id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='custommetatags',
            name='mtg_id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='e_id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='geopolitical',
            name='e_id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='infograph',
            name='c_id',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='infograph',
            name='i_id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='infograph',
            name='p_id',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='infograph',
            name='source_id',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='infograph',
            name='status_id',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='mastertopics',
            name='master_topic',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='mastertopics',
            name='master_topic_code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='mastertopics',
            name='mt_id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='parentinfograph',
            name='p_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='pid'),
        ),
        migrations.AlterField(
            model_name='topics',
            name='mt_id',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='topics',
            name='t_id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='topics',
            name='topic_code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
