# Generated by Django 2.0.2 on 2018-03-09 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0003_auto_20180309_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infograph',
            name='appsource',
        ),
        migrations.RemoveField(
            model_name='infograph',
            name='appstatus',
        ),
        migrations.RemoveField(
            model_name='infograph',
            name='infograph_category',
        ),
        migrations.RemoveField(
            model_name='infograph',
            name='parentinfograph',
        ),
        migrations.AlterField(
            model_name='infographcategory',
            name='c_id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
