# Generated by Django 2.0.2 on 2018-03-09 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0004_auto_20180309_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='user_type_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='newsroom.UserType'),
            preserve_default=False,
        ),
    ]
